class HelicopterRunner
{
	public static void main(String[] values)
	{
		System.out.println("starts HelicopterRunner");
		Helicopter helicopter=new Helicopter();
		Helicopter heli=new Helicopter();
		Helicopter copter=new Helicopter();
		Helicopter helicop=new Helicopter();
		Helicopter helicopters=new Helicopter();
		Market market=new Market();
		Market mark=new Market();
		Market ket=new Market();
		Market mars=new Market();
		Market markets=new Market();
		Mall mall=new Mall();
		Mall malls=new Mall();
		Mall mal=new Mall();
		Mall mallValue=new Mall();
		Mall mallValues=new Mall();
		Train train=new Train();
		Train trainValue=new Train();
		Train trainValues=new Train();
		Train trains=new Train();
		Train training=new Train();
		Ring ring=new Ring();
		Ring rings=new Ring();
		Ring ringValue=new Ring();
		Ring ringValues=new Ring();
		Ring ringsValue=new Ring();
		Auto auto=new Auto();
		Auto autos=new Auto();
		Auto autoValue=new Auto();
		Auto autoValues=new Auto();
		Auto autosValues=new Auto();
		Auditorium auditorium=new Auditorium();
		Auditorium audi=new Auditorium();
		Auditorium audit=new Auditorium();
		Auditorium auditoriumValue=new Auditorium();
		Auditorium auditoriumValues=new Auditorium();
		SpaceShip spaceShip=new SpaceShip();
		SpaceShip space=new SpaceShip();
		SpaceShip ship=new SpaceShip();
		SpaceShip spaceShipValue=new SpaceShip();
		SpaceShip spaceShipValues=new SpaceShip();
		Alien alien=new Alien();
		Alien aliens=new Alien();
		Alien alienValue=new Alien();
		Alien alienValues=new Alien();
		Alien aliensValue=new Alien();
		Bullet bullet=new Bullet();
		Bullet bulletValue=new Bullet();
		Bullet bulletValues=new Bullet();
		Bullet bulletsValue=new Bullet();
		Bullet bullets=new Bullet();
		Galaxy galaxy=new Galaxy();
		Galaxy galaxies=new Galaxy();
		Galaxy galaxyValue=new Galaxy();
		Galaxy galaxyValues=new Galaxy();
		Galaxy galaxiesvalues=new Galaxy();
		Spoon spoon=new Spoon();
		Spoon spoons=new Spoon();
		Spoon spoonValue=new Spoon();
		Spoon spoonValues=new Spoon();
		Spoon spoonsValues=new Spoon();
		BlackHole blackHole=new BlackHole();
		BlackHole blackHoles=new BlackHole();
		BlackHole black=new BlackHole();
		BlackHole Hole=new BlackHole();
		BlackHole blackHoleValues=new BlackHole();
		Cake cake=new Cake();
		Cake cakes=new Cake();
		Cake cakeValue=new Cake();
		Cake cakeValues=new Cake();
		Cake cakesValues=new Cake();
		Wrapper wrapper=new Wrapper();
		Wrapper wrappers=new Wrapper();
		Wrapper wrappersValue=new Wrapper();
		Wrapper wrappersValues=new Wrapper();
		Wrapper wrapperValue=new Wrapper();
		System.out.println("ends HelicopterRunner");
	}
}