class ObjectRunner
{
	public static void main(String[] args)
	{
		String firstName="Bhavya";
		System.out.println(firstName); 
		String lastName="Shree";
		System.out.println(lastName); 
		String city="Bangalore";
		System.out.println(city);
        String state = "Karnataka";
		System.out.println(state);
        String zipCode = "563101";
		System.out.println(zipCode);
		String Education="Engineering";
		System.out.println(Education);
		String currency = "Rupee";
		System.out.println(currency);
		String employeeID = "E12345";
		System.out.println(employeeID);
		String jobTitle = "Software Engineer";
		System.out.println(jobTitle);
        String company = "Capgemini";
		System.out.println(company);
		String department = "Engineering";
		System.out.println(department);
		String  gender= " Female";
		System.out.println("gender:"+gender);
        String hairColor="Black";
        String transactionID = "TXN-2023-001";
		System.out.println(transactionID);
        String shippingAddress = "456 Elm St";
		System.out.println(shippingAddress);
        String billingAddress = "789 Oak Ave";
		System.out.println(billingAddress);
		String username = "bhavyashree";
		System.out.println(username);
        String my_password = "Bhavya@123";
		System.out.println(my_password);
		String language = "English";
		System.out.println(language);
        String countryOfMine = "India ";
		System.out.println(countryOfMine);
        String internationalCode = "+1";
		System.out.println(internationalCode);
		String trainingInstitute="x-workz";
		System.out.println(trainingInstitute);
		String major = "Computer Science";
		System.out.println("major:"+major);
        String minor = "Mathematics";
		System.out.println(minor);
		String articleTitle = "Richman poorman";
		System.out.println(articleTitle);
		String favoriteSport="Cricket";
		System.out.println(favoriteSport);
        String authorName = "Alice Brown";
		System.out.println(authorName);
		String workshopTitle = "AI and Machine Learning";
		System.out.println(workshopTitle);
        String departmentCode = "ENG";
		System.out.println(departmentCode);
		String eventTitle = "Annual Tech Conference";
		System.out.println(eventTitle);
		String USN = "1CD20AI009";
		System.out.println(USN);
		String verificationCode = "123456";
		System.out.println(verificationCode);
        String accessToken = "abc123xyz456";
		System.out.println(accessToken);
        String userRole = "Administrator";
		System.out.println(userRole);
        String accessLevel = "Full Access";
		System.out.println(accessLevel);
		String myAccessLevel = "Full Access";
		System.out.println(myAccessLevel);
		String welcomeMessage = "Welcome to Tech Solutions!";
		System.out.println(welcomeMessage);
        String gratitudeMessage = "Thank you";
		System.out.println(gratitudeMessage);
        String finalMessage = "Goodbye";
		System.out.println(finalMessage);
		String scientist = "Charlews Babagge";
		System.out.println("scientist:"+scientist);
		String favoriteChats="Pani Puri";
		System.out.println(favoriteChats);
        String holidayGreeting = "Happy Holidays!";
		System.out.println(holidayGreeting);
        String birthdayGreeting = "Happy Birthday!";
		System.out.println(birthdayGreeting);
        String anniversaryGreeting = "Happy Anniversary!";
		System.out.println(anniversaryGreeting);
		String libraryCardNumber = "20AI009";
		System.out.println(libraryCardNumber);
		System.out.println(libraryCardNumber+"is my library card number");
        String noOfRainbowColors = "Seven";
		System.out.println(noOfRainbowColors);
        String bookTitle = "Introduction to Algorithms";
		System.out.println("bookTitle:"+bookTitle);
		String karnatakaCapital="Bangalore";
		System.out.println("karnatakaCapital:"+karnatakaCapital);
		String favoriteFruit="Apple";
		System.out.println("favoriteFruit:"+favoriteFruit);
        String author = "Thomas H. Cormen";
		System.out.println("author:"+author);
        String publicationYear = "2022";
		System.out.println(publicationYear);
		String favoriteFood="poori";
		System.out.println(favoriteFood);
        String libraryBranch = "Downtown";
		String healthInsuranceProvider = "Global Health";
		System.out.println(healthInsuranceProvider);
		String phoneName = "RedmiNote 10S";
		System.out.println(phoneName);
        String genderCat="Female";
		System.out.println(genderCat);
		String myFavoritePlace="France";
		String favoriteJob="Software Engineer";
      	System.out.println(favoriteJob);
		String missileManOfIndia="Abdul Kalam";
      	System.out.println(missileManOfIndia);
        String collegeName="Cambridge";
      	System.out.println(collegeName);
		String favoriteGod="Ganesha";
      	System.out.println(favoriteGod);
		String indiaCapital="delhi";
      	System.out.println(indiaCapital);
		String yellowfruit="Banana";
      	System.out.println(yellowfruit);
		String godOfCricket="Sachin";
      	System.out.println(godOfCricket);
		String cricketCaptain="Rohit Sharma";
      	System.out.println(cricketCaptain);
		
		String fullName="Bhavya Shree";
		System.out.println("my name is:"+fullName);
		String email="bhavyashreecs2002";
		System.out.println("my emailid is:"+email+"@gmail.com");
		String password="Bhavya@123";
		System.out.println("my emailid password is:"+password);
		String maildetails="bhavyashreecs2002";
		System.out.println("my mail is:"+maildetails+"and its password is"+password);
		String favoritePlace="France";
		System.out.println("my favorite place is:"+favoritePlace+" and I would like to go there");
		String nativePlace="India";
		System.out.println("my birth place is:"+nativePlace);
		String requiredkeyForSuccess="dedication";
		System.out.println("key for Success are:"+requiredkeyForSuccess);
		String keyForSuccess="honesty";
		System.out.println("key for Success are:"+keyForSuccess+"and also"+requiredkeyForSuccess);
		String capitalCity="Bangalore";
		System.out.println(capitalCity+"is the capital city of karnataka");
		String Indiacapital="Delhi";
		System.out.println(Indiacapital+"is the capital city of India");
		String noOfAlbhabets="26";
		System.out.println(missileManOfIndia+"is known as missile man of India");
      	System.out.println("there are"+noOfAlbhabets+"in english");
		String cricketCaptainOfIndia="Rohit Sharma";
		System.out.println(cricketCaptainOfIndia+"is captain of Indian cricket");
		String fruityellow=" Banana";
		System.out.println(fruityellow+"is a fruit in yellow color");
		String myCountry=" India";
		System.out.println(myCountry+"is known for its traditional");
		String myPhone = "RedmiNote 10S";
		System.out.println("I am using"+myPhone);
		String RainbowColors = "Seven";
		System.out.println("There are "+RainbowColors+"rainbow colors");
		String location="Bangalore";
		System.out.println("my residential location is  "+location);
		String phoneNumber="6362411289";
		System.out.println("my phone Number is  "+phoneNumber);
		String welcomeMsg = "Welcome to Tech Solutions!";
		System.out.println("we will welcome someone by greeting"+welcomeMsg);
        String thankYouMessage = "Thank you for your help!";
		System.out.println("we will thank someone by telling"+thankYouMessage);
        String farewellMessage = "Goodbye and good luck!";
		System.out.println("last message for farewell is"+farewellMessage);
		String bankName="Canara";
		System.out.println("I have my account in: " + bankName+"bank");
		String sportsPerson="Dhoni";
		System.out.println("My favorite sports Person is: " + sportsPerson);
		String brother="Bhanu";
		System.out.println(brother+"is my brother name");
		String refreshToken = "xyz456abc123";
		System.out.println("refreshToken:"+refreshToken);
		String nameOfSchool="Spoorthi";
      	System.out.println("I studied in :"+nameOfSchool+"high school");
		String myCollegeName="cambridge";
      	System.out.println("I studied in :"+myCollegeName);
		String god="Ganesha";
      	System.out.println(god+"is my favorite god");
		System.out.println(favoriteFood+"is my favoriteFood");
		String powerfulGod="Lord Shiva";
      	System.out.println(powerfulGod+"is powerful God");
		String star="Sun";
      	System.out.println(star+"is one of the star");
		String mother="Siddalingeshwara";
		System.out.println(mother+"is my mother name");
		String planet="Earth";
      	System.out.println(planet+"is the planet that we are living");
		String animal="Fish";
      	System.out.println(animal+"is water animal ");
		String petAnimal="Dog";
      	System.out.println(petAnimal+"is known as the favorite pet animal for people ");
		String continent="asia";
      	System.out.println(continent+"is the continent that we are living");
		String bone="206";
		System.out.println("There are"+bone+"bones in out body");
		String father="Siddalingeshwara";
		System.out.println(father+"is my father name");
		String myLanguage="Hindi";
		System.out.println(myLanguage+"is national language of India");
		String match="T20";
		System.out.println("India won"+match+"match");
		String Earth="third";
		System.out.println("Earth is the"+Earth+"planet in our solar system");
		String naturalSatellite="Moon";
		System.out.println(naturalSatellite+"is the natural satellite of earth");
		String myFavoriteChats="Pani Puri";
		System.out.println(myFavoriteChats);
		String departmentCodeOfEnglish = "ENG";
		System.out.println(departmentCodeOfEnglish+"is the department Code of english");
		String myPassword="Bhavya@123";
		System.out.println("my emailid password is:"+myPassword);
		String myFavoriteSpot = "Nandhi Hills";
		System.out.println(myFavoriteSpot+"is my favorite spot");
		System.out.println(language+"is the international language");
		String cycle = "Day and night";
		System.out.println(cycle+"completes one day");
		String planetNo="Mars";
		System.out.println(planetNo+" is the first planet in our solar system");
		String code=zipCode+"is the code of karnataka";
		System.out.println(code);
		String fullname=firstName+lastName;
		System.out.println("my full name is"+fullname);
		String schoolName="Spoorthi";
      	System.out.println("I studied in :"+schoolName);
		System.out.println(author+"is an english author");
		String myId =employeeID+"is my id";
		System.out.println(myId);
		String country=city+"is the silicon city";
		System.out.println(country);
		String degree=Education+"is a professional degree";
		System.out.println(degree);
		String reviewStatus = "Under Review";
		System.out.println("reviewStatus:"+reviewStatus);
		System.out.println(myFavoritePlace);
		System.out.println(myFavoritePlace+"is my favorite place");
		System.out.println(libraryCardNumber+"is my library card number");
		String IndianCurrency=currency+"is the indian Currency";
		System.out.println(IndianCurrency);
		String favoriteSpot = "Nandhi Hills";
		System.out.println("favoriteSpot:"+favoriteSpot);
		String apiVersion = "v1.2.3";
		System.out.println("apiVersion:"+apiVersion);
		String reasonForHoliday = "Sick Leave";
		System.out.println("reasonForHoliday:"+reasonForHoliday);
		String libraryName = "Tech Library";
		System.out.println("libraryName:"+libraryName);
		String emergencyContactName = "Mary Johnson";
		System.out.println("emergencyContactName:"+emergencyContactName);
		String paymentMethod = "Credit Card";
		System.out.println("paymentMethod:"+paymentMethod);
		System.out.println("libraryBranch:"+libraryBranch);
		System.out.println(libraryBranch+"is one of the known library branch");
		String favoriteDress="Kurtha";
      	System.out.println("favoriteDress:"+favoriteDress);
		String manager = "Jane Smith";
		System.out.println("manager:"+manager);
	}
}